name: Analyze Flutter Code

on: [push]

jobs:
  flutter_analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.19.5
    - name: install dependencies
      run: flutter pub get
    - name: analyze
      run: flutter analyze
